### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by zhaijack** [apache/distributedlog#167]
Tracking the checklist for completing release 0.5.0
- [x] code refine
    - [X] Code cleanup for 0.5.0 release #166 
- [x] Release Notes (feature highlights) #168 
- [x] Documentation for new features #170

**Comment by sijie** [comment]
I linked #166 here - this issue is to clean up API code to make sure we have a clean API for 0.5.0 release.

**Comment by sijie** [comment]
assigned to @zhaijack since he is the release manager for 0.5.0

**Comment by zhaijack** [comment]
close it
